services:
  - type: web
    name: todo-backend
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        value: https://todo.vercel.app
      - key: PORT
        value: 1000